// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX4Tu1VwkyLKQUl_OKvYddJXGlUeE57b4',
    appId: '1:38014690112:web:2baa88b3450a624823d0a5',
    messagingSenderId: '38014690112',
    projectId: 'digipass-8ce3a',
    authDomain: 'digipass-8ce3a.firebaseapp.com',
    storageBucket: 'digipass-8ce3a.appspot.com',
    measurementId: 'G-T2XG3ZJ0F4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCjzpD-YceCmLc5evkh9krxjqf7sRPcIQ',
    appId: '1:38014690112:android:a45f98485acc6afb23d0a5',
    messagingSenderId: '38014690112',
    projectId: 'digipass-8ce3a',
    storageBucket: 'digipass-8ce3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO8x9NYkGcEI3MrY2dFBhiBOA-yAvYofU',
    appId: '1:38014690112:ios:d3618b260b8c9e8b23d0a5',
    messagingSenderId: '38014690112',
    projectId: 'digipass-8ce3a',
    storageBucket: 'digipass-8ce3a.appspot.com',
    androidClientId: '38014690112-stguvsc4ootj4r8osq7dtf9imap7cd9q.apps.googleusercontent.com',
    iosClientId: '38014690112-noru7v5t7c0jko0v29a4sbhnirrv73vt.apps.googleusercontent.com',
    iosBundleId: 'com.EitanandJosh.DigiPass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO8x9NYkGcEI3MrY2dFBhiBOA-yAvYofU',
    appId: '1:38014690112:ios:d3618b260b8c9e8b23d0a5',
    messagingSenderId: '38014690112',
    projectId: 'digipass-8ce3a',
    storageBucket: 'digipass-8ce3a.appspot.com',
    androidClientId: '38014690112-stguvsc4ootj4r8osq7dtf9imap7cd9q.apps.googleusercontent.com',
    iosClientId: '38014690112-noru7v5t7c0jko0v29a4sbhnirrv73vt.apps.googleusercontent.com',
    iosBundleId: 'com.EitanandJosh.DigiPass',
  );
}
