name: Flutter iOS Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Flutter
        run: brew install --cask flutter
        
      - name: Change Flutter Branch
        run: flutter channel dev
        
      - name: Run flutter doctor
        run: flutter doctor
        
      - name: Run flutter pub get
        run: flutter pub get
        
      - name: Prepare signing
  # You may pin to the exact commit or the version.
  # uses: ngeri/prepare-signing@5bec954468cce224f0d7f589dbe42596dbaf48f0
        uses: ngeri/prepare-signing@v1.0.2
        with:
          # App Store Connect private key with proper rights
          appStoreConnectPrivateKey: ${{ secrets.APC_PRIVATE_KEY }}
          # Identifier of the private key
          keyID: 3S697P578G
          # Issuer identifier
          issuerID: 0690e069-9ae9-41cf-8298-5d31d85c9b8d
          # Id of the newly created temporary kechain
          keychainName: signing.ios
          # Password of the newly created temporary kechain
          keychainPassword: signing.ios
          # Base64 encoded .p12 signing cert with private key
          base64P12File: ${{ secrets.P12_CERT }}
          # Password of the .p12 file
          p12Password: ${{ secrets.P12_PASSWORD }}
          # Bundle identifier of the application
          bundleIdentifier: com.EitanandJosh.DigiPass
          # E.g.: IOS_APP_DEVELOPMENT, IOS_APP_STORE etc.
          signType: IOS_APP_STORE
      - name: Download Distribution Profiles
  # You may pin to the exact commit or the version.
  # uses: Apple-Actions/download-provisioning-profiles@3167792207a5b26099bc0ca22b5010a323dd2a0b
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          # The bundle identifier of the application
          bundle-id: com.EitanandJosh.DigiPass
          # The type of profile to download. One of IOS_APP_DEVELOPMENT, IOS_APP_STORE, IOS_APP_ADHOC, IOS_APP_INHOUSE, MAC_APP_DEVELOPMENT, MAC_APP_STORE, MAC_APP_DIRECT, TVOS_APP_DEVELOPMENT, TVOS_APP_STORE, TVOS_APP_ADHOC, TVOS_APP_INHOUSE
          profile-type: IOS_APP_STORE
          # The AppStore Connect API Key Issuer Identifier
          issuer-id: 0690e069-9ae9-41cf-8298-5d31d85c9b8d
          # The Key ID for AppStore Connect API
          api-key-id: 3S697P578G
          # The PKCS8 format Private Key for AppStore Connect API
          api-private-key: ${{ secrets.APC_PRIVATE_KEY }}
          
      - name: Download Development Profiles
  # You may pin to the exact commit or the version.
  # uses: Apple-Actions/download-provisioning-profiles@3167792207a5b26099bc0ca22b5010a323dd2a0b
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          # The bundle identifier of the application
          bundle-id: com.EitanandJosh.DigiPass
          # The type of profile to download. One of IOS_APP_DEVELOPMENT, IOS_APP_STORE, IOS_APP_ADHOC, IOS_APP_INHOUSE, MAC_APP_DEVELOPMENT, MAC_APP_STORE, MAC_APP_DIRECT, TVOS_APP_DEVELOPMENT, TVOS_APP_STORE, TVOS_APP_ADHOC, TVOS_APP_INHOUSE
          profile-type: IOS_APP_DEVELOPMENT
          # The AppStore Connect API Key Issuer Identifier
          issuer-id: 0690e069-9ae9-41cf-8298-5d31d85c9b8d
          # The Key ID for AppStore Connect API
          api-key-id: 3S697P578G
          # The PKCS8 format Private Key for AppStore Connect API
          api-private-key: ${{ secrets.APC_PRIVATE_KEY }}    
          
      - name: Prep iOS Flutter tools
        run: flutter build ios --release --no-codesign
      
      - name: Archive Xcode Project
        run: xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -config Release -archivePath build/ios/xcarchive/Runner1.xcarchive archive COMPILER_INDEX_STORE_ENABLE=NO DEVELOPMENT_TEAM=A72ZC8AJ5X 'CODE_SIGN_IDENTITY=iPhone Distribution'
        
      - name: Export Archive to .ipa
        run: xcodebuild -exportArchive -archivePath build/ios/xcarchive/Runner1.xcarchive -exportPath build/ios/ipa -exportOptionsPlist exportOptions.plist COMPILER_INDEX_STORE_ENABLE=NO
      - name: List files
        run: cd build/ios/ipa && ls
      - name: Upload app to TestFlight
  # You may pin to the exact commit or the version.
  # uses: Apple-Actions/upload-testflight-build@54dc215b4cd5529730db39f11c84efdb71414e07
        uses: Apple-Actions/upload-testflight-build@v1
        with:
    # The path to the app (ipa etc)
          app-path: /build/ios/ipa/Runner.ipa
    # The type of app to upload (osx | ios | appletvos)
          app-type: ios
    # The AppStoreConnect API Key Issuer Identifier
          issuer-id: 0690e069-9ae9-41cf-8298-5d31d85c9b8d
    # The Key ID for AppStore Connect API
          api-key-id: 3S697P578G
    # The PKCS8 format Private Key for AppStore Connect API
          api-private-key: ${{ secrets.APC_PRIVATE_KEY }}
     
